package com.example.laboratorinis1.mybatis.dao;

import com.example.laboratorinis1.mybatis.model.Mokykla;
import com.example.laboratorinis1.mybatis.model.Mokytojas;
import org.mybatis.cdi.Mapper;

import java.util.List;
import java.util.Set;

@Mapper
public interface MokytojasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOKYTOJAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOKYTOJAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    int insert(Mokytojas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOKYTOJAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    Mokytojas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOKYTOJAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    List<Mokytojas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOKYTOJAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    int updateByPrimaryKey(Mokytojas record);

    Set<Mokykla> selectSchoolsInTeachers(long teacherId);
}