package com.example.laboratorinis1.mybatis.dao;

import com.example.laboratorinis1.mybatis.model.Pamoka;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface PamokaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PAMOKA
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PAMOKA
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    int insert(Pamoka record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PAMOKA
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    Pamoka selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PAMOKA
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    List<Pamoka> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PAMOKA
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    int updateByPrimaryKey(Pamoka record);
}