package com.example.laboratorinis1.mybatis.model;

import java.util.Set;

public class Mokytojas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOKYTOJAS.ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOKYTOJAS.PAVARDE
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    private String pavarde;

    private Set<Mokykla> mokyklos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOKYTOJAS.VARDAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    private String vardas;

    public Set<Mokykla> getMokyklos() {
        return mokyklos;
    }

    public void setMokyklos(Set<Mokykla> mokyklos) {
        this.mokyklos = mokyklos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOKYTOJAS.ID
     *
     * @return the value of PUBLIC.MOKYTOJAS.ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOKYTOJAS.ID
     *
     * @param id the value for PUBLIC.MOKYTOJAS.ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOKYTOJAS.PAVARDE
     *
     * @return the value of PUBLIC.MOKYTOJAS.PAVARDE
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public String getPavarde() {
        return pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOKYTOJAS.PAVARDE
     *
     * @param pavarde the value for PUBLIC.MOKYTOJAS.PAVARDE
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public void setPavarde(String pavarde) {
        this.pavarde = pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOKYTOJAS.VARDAS
     *
     * @return the value of PUBLIC.MOKYTOJAS.VARDAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public String getVardas() {
        return vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOKYTOJAS.VARDAS
     *
     * @param vardas the value for PUBLIC.MOKYTOJAS.VARDAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public void setVardas(String vardas) {
        this.vardas = vardas;
    }
}