package com.example.laboratorinis1.mybatis.model;

import java.util.Set;

public class Mokykla {
    private Set<Mokytojas> mokytojuPamokos;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOKYKLA.ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOKYKLA.PAVADINIMAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    private String pavadinimas;

    public Set<Mokytojas> getMokytojuPamokos() {
        return mokytojuPamokos;
    }

    public void setMokytojuPamokos() {
        this.mokytojuPamokos = mokytojuPamokos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOKYKLA.ID
     *
     * @return the value of PUBLIC.MOKYKLA.ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOKYKLA.ID
     *
     * @param id the value for PUBLIC.MOKYKLA.ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOKYKLA.PAVADINIMAS
     *
     * @return the value of PUBLIC.MOKYKLA.PAVADINIMAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public String getPavadinimas() {
        return pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOKYKLA.PAVADINIMAS
     *
     * @param pavadinimas the value for PUBLIC.MOKYKLA.PAVADINIMAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public void setPavadinimas(String pavadinimas) {
        this.pavadinimas = pavadinimas;
    }
}