package com.example.laboratorinis1.mybatis.model;

public class Pamoka {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PAMOKA.ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PAMOKA.PAVADINIMAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    private String pavadinimas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PAMOKA.MOKYKLOS_ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    private Long mokyklosId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PAMOKA.MOKYTOJO_ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    private Long mokytojoId;

    private Mokytojas mokytojas;
    private Mokykla mokykla;

    public Mokytojas getMokytojas() {return mokytojas;}
    public void setMokytojas(Mokytojas mokytojas) {this.mokytojas = mokytojas;}

    public Mokykla getMokykla() {return mokykla;}
    public void setMokykla(Mokykla mokykla) {this.mokykla = mokykla;}


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PAMOKA.ID
     *
     * @return the value of PUBLIC.PAMOKA.ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PAMOKA.ID
     *
     * @param id the value for PUBLIC.PAMOKA.ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PAMOKA.PAVADINIMAS
     *
     * @return the value of PUBLIC.PAMOKA.PAVADINIMAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public String getPavadinimas() {
        return pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PAMOKA.PAVADINIMAS
     *
     * @param pavadinimas the value for PUBLIC.PAMOKA.PAVADINIMAS
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public void setPavadinimas(String pavadinimas) {
        this.pavadinimas = pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PAMOKA.MOKYKLOS_ID
     *
     * @return the value of PUBLIC.PAMOKA.MOKYKLOS_ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public Long getMokyklosId() {
        return mokyklosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PAMOKA.MOKYKLOS_ID
     *
     * @param mokyklosId the value for PUBLIC.PAMOKA.MOKYKLOS_ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public void setMokyklosId(Long mokyklosId) {
        this.mokyklosId = mokyklosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PAMOKA.MOKYTOJO_ID
     *
     * @return the value of PUBLIC.PAMOKA.MOKYTOJO_ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public Long getMokytojoId() {
        return mokytojoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PAMOKA.MOKYTOJO_ID
     *
     * @param mokytojoId the value for PUBLIC.PAMOKA.MOKYTOJO_ID
     *
     * @mbg.generated Wed Apr 12 11:55:58 EEST 2023
     */
    public void setMokytojoId(Long mokytojoId) {
        this.mokytojoId = mokytojoId;
    }
}